[font]
size = 16

[font.offset]
x = 0
y = -4

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.7
title = "Alacritty"

[window.padding]
x = 8
y = 18

[keyboard]
bindings = [
   {key = "Return", mods = "Shift", action = "SpawnNewInstance" }
]
