#!/bin/bash

    while true
    do
        export DISPLAY=:0.0
        battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
        if on_ac_power; then
            if [ $battery_level -ge 50 ]; then
                notify-send "Unplug the AC adapter." "Charging: ${battery_level}% "
             fi
        fi

        sleep 300 # 300 seconds or 5 minutes
    done

