#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Default cursor
xsetroot -cursor_name left_ptr

# Autostart programs
~/.config/scripts/autostart/autostart.sh

bspc monitor -d I II III IV V VI VII VIII IX X XI XII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a qbittorrent desktop='^11'
bspc rule -a pavucontrol desktop='^10'
bspc rule -a easyeffects desktop='^10'
