#!/usr/bin/zsh

#mode changing to
mode=$1
echo $1
#current mode
c_mode=$(< ~/scripts/function/mode)

i3-msg "mode default"

#on-change-back
if [ $c_mode -eq 1 ]
then
    echo "1"
elif [ $c_mode -eq 2 ]
then
    echo "2"
elif [ $c_mode -eq 3 ]
then
    echo "3"
elif [ $c_mode -eq 4 ]
then
    xcalib .config/gamma_1.icc
    xcalib -gc 1.1 -a
    light -U 10
elif [ $c_mode -eq 5 ]
then 
    echo "5"
elif [ $c_mode -eq 6 ]
then
    echo "6" 
elif [ $c_mode -eq 7 ]
then
    echo "7"
fi

#on-change
if [ $mode -eq 1 ]
then
    echo "1" > ~/scripts/function/mode
elif [ $mode -eq 2 ]
then
    echo "2" > ~/scripts/function/mode
elif [ $mode -eq 3 ]
then
    echo "3" > ~/scripts/function/mode
    easyeffects -l Song
    if [ $c_mode -eq 4 ]
    then
    pactl set-sink-volume @DEFAULT_SINK@ +20%   
    fi

elif [ $mode -eq 4 ]
then
    echo "4" > ~/scripts/function/mode
    easyeffects -l Film
    if [ $c_mode -eq 3 ]
    then
    pactl set-sink-volume @DEFAULT_SINK@ -20%
    fi

    #Change gamma for movies and brightness
    xcalib .config/gamma_1.icc
    xcalib -gc 1.5 -a
    light -A 10

elif [ $mode -eq 5 ]
then 
    echo "5" > ~/scripts/function/mode
elif [ $mode -eq 6 ]
then
    echo "6" > ~/scripts/function/mode
elif [ $mode -eq 7 ]
then
    echo "7" > ~/scripts/function/mode
fi

