#!/usr/bin/zsh
mode=$(< ~/scripts/function/mode)
i3-msg mode "default"
if [ $mode -eq 1 ]
then
    echo "Default"
elif [ $mode -eq 2 ]
then
    echo "Work"
elif [ $mode -eq 3 ]
then
    mpc clear;mpc load fast\ beats;mpc play
elif [ $mode -eq 4 ]
then
    thunar Videos/Anime 
elif [ $mode -eq 5 ]
then 
    alacritty&|
elif [ $mode -eq 6 ]
then
    echo "Shutdown"
elif [ $mode -eq 7 ]
then
    pkill firefox
fi
