#!/usr/bin/zsh
mode=$(< ~/scripts/function/mode)
i3-msg "mode default"
if [ $mode -eq 1 ]
then
    echo "Default"
elif [ $mode -eq 2 ]
then
    echo "Work"
elif [ $mode -eq 3 ]
then
    easyeffects -l Song
elif [ $mode -eq 4 ]
then
    thunar Videos
elif [ $mode -eq 5 ]
then 
    echo "Programming"
elif [ $mode -eq 6 ]
then
    echo "Shutdown"
elif [ $mode -eq 7 ]
then
    echo "Gaming"
fi
