#!/usr/bin/zsh
mode=$(< ~/scripts/function/mode)
i3-msg "mode default"
if [ $mode -eq 1 ]
then
    pkill btm
    pkill deluge
    pkill ncmpcpp
    pkill cava
    pkill easyeffects
elif [ $mode -eq 2 ]
then
    echo "Work"
elif [ $mode -eq 3 ]
then
    easyeffects -l Song
elif [ $mode -eq 4 ]
then
    thunar Videos
elif [ $mode -eq 5 ]
then
    code
elif [ $mode -eq 6 ]
then
    alacritty --command ~/scripts/function/reboot 
elif [ $mode -eq 7 ]
then
    echo "Gaming"
fi
