#!/usr/bin/zsh
mode=$(< ~/scripts/function/mode)
i3-msg mode "default"
if [ $mode -eq 1 ]
then
    ssid=$(iwgetid -r)
    if [ "$ssid" = "ESS" ]
    then
        nmcli device wifi list;
        nmcli device wifi connect ESS_5Ghz
    else
        nmcli device wifi list;
        nmcli device wifi connect ESS
    fi
elif [ $mode -eq 2 ]
then
    echo "Work"
elif [ $mode -eq 3 ]
then
    easyeffects -l Low_bass
elif [ $mode -eq 4 ]
then
    echo "Anime"
elif [ $mode -eq 5 ]
then 
    echo "Programming"
elif [ $mode -eq 6 ]
then
    echo "Shutdown"
elif [ $mode -eq 7 ]
then
    echo "Gaming"
fi
