#!/bin/bash
i3-msg "floating toggle"
i3-msg "resize shrink height 200 px"
dialog --title "Hibernate" \
--backtitle "" \
--yesno "Are you sure you want to hibernate?" 7 60

# Get exit status
# 0 means user hit [yes] button.
# 1 means user hit [no] button.
# 255 means user hit [Esc] key.
response=$?
case $response in
   0) pkill firefox;pkill Discord;zsh ~/scripts/function/change_f 1;systemctl hibernate;;
   1) ;;
   255)  ;;
esac
kill -9 $PPID
