#!/usr/bin/zsh
curr=$(i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2)
prev=$(< ~/scripts/function/prev_desktop)
curr2=$(< ~/scripts/function/curr_desktop)
mode=$(< ~/scripts/function/mode)
if [ "$mode" != 5 ]
then
    i3-msg workspace back_and_forth
elif [ $curr != $curr2 ]
then
    i3-msg workspace $curr2
elif [ $curr != $prev ]
then
    i3-msg workspace $prev
    touch ~/scripts/function/prev_desktop
    touch ~/scripts/function/curr_desktop
    echo $prev > ~/scripts/function/curr_desktop
    echo $curr > ~/scripts/function/prev_desktop
fi

