#!/bin/bash

########################################################################################################
# AUTHOR - Niranjan Ravichandra, @nravic							       #
# display cover w/ feh, rotates as slideshow. Place under ncmpcpp "execute_on_song_change."            #
########################################################################################################

killall -9 feh > /dev/null 2&>1 #kill all instances of feh at the beginning of script

coverdisplay ()
{
    killall -g feh > /dev/null 2&>1 
    MUSIC_DIR=Music/
    
    tmp_filepath=$(mpc -f %file%) #grab path of currently playing file
    #bash string manipulation shenanigans
    muspath=${tmp_filepath%%[*}
    filepath=$MUSIC_DIR$muspath
    path=${filepath//" "/"\ "}
    PATH_NO_TRAIL=$(echo "$path" | xargs)

    feh -x -g 400x400 -Z "$PATH_NO_TRAIL" > /dev/null 2&>1
    echo  $PATH_NO_TRAIL
    #kill feh on song change
    if mpc current --wait > /dev/null 2&>1
    then
	killall -g feh > /dev/null 
	feh -x -g 400x400 -Z "$PATH_NO_TRAIL" >/dev/null 2&>1 
    fi
}

coverdisplay
exit
