#!/usr/bin/zsh
in=$1
out=$1"720"
mkdir $out
for file in $in/**/*(.)
do
    outfile=$out${file#"$in"}
    if [ ! -f $outfile ]; then
        ffmpeg -i $file -vf scale=-2:480 -c:v libx264 -crf 20 -preset superfast -threads 4 -c:a copy $outfile
    fi
done

