#!/usr/bin/zsh

rm ~/scripts/wall_order
touch ~/scripts/wall_order
walls=()
for i in "$1"/*
do
    walls+=($i)
done
walls=$(shuf -e "${walls[@]}")
for i in ${walls[@]}
do
    echo "$i" >> ~/scripts/wall_order
done
