#!/usr/bin/zsh
a9="80673118-39c0-4c17-87e2-8da4b79df80c"
decp=$(qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.ActivityDescription $a9)
qdbus org.kde.ActivityManager /ActivityManager/Activities SetCurrentActivity $a9
if [ $decp = "off" ]
then
	qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.SetActivityDescription $a9 "on"
	sleep 0.1;
 	firefox -new-window "web.whatsapp.com"
fi
