#!/usr/bin/zsh
ca=$(qdbus org.kde.ActivityManager /ActivityManager/Activities CurrentActivity)
a9="80673118-39c0-4c17-87e2-8da4b79df80c"
a11="43bb1ac8-793a-479b-b7d7-d52a3248d7ff"
a3="bdeb513a-3f19-4fc9-b49e-f48c93df2014"
activity=$(<.activity_created)
if [ $ca = $a9 ] || [ $ca = $a11 ] #9th activity or 11th
then
	qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.SetActivityDescription $ca off
fi
if [ $ca = $a3 ]
then
	d=$(qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.ActivityDescription $a3);
#	if [ "$d" != "off" ]
#	then
#k		prs=$(pgrep alacritty)
#		pr=0;
#		for i in $prs;do
#			((v1=$d-$pr));((v2=$d-$i));
#			if [ $v1 -lt $v2 ]
#			then
#				$pr=$i
#			fi
#		done
#		notify-send $pr;
		#kill -9 $pr;
#		qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.SetActivityDescription $ca off;
#	fi
	pkill vlc;
fi
activites=()
d=0
setopt shwordsplit  
for i in $activity; do
	if [ $ca = $i ]
	then
		d=1
		xdotool key Meta + Tab;sleep 0.5;qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.RemoveActivity $ca
	else
		activites+="$i" 
	fi		
done
unsetopt shwordsplit
echo "$activites" > ".activity_created"
if [ $d -eq 0 ] 
then
xdotool key Meta + Tab;sleep 0.5;qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.StopActivity $ca;
fi
